include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**.g.dart"
    - "**.freezed.dart"
    - "**.gr.dart"
    - "**.config.dart"
    - "pubspec.yaml"

linter:
  rules:
    public_member_api_docs: false
